### DISCUSSION TITLE
Add "why we need nanocl" in readme

### DISCUSSION THREAD

**Discussion by gftea** [nxthat/nanocl#324] [General]
Hi,

I am impressive with the work started here, I would like to understand why we need "nanocl" vs  "something, e.g. k8s or others"
This is first question come to my mind when I discover this project

**Comment by mamaicode** [comment]
@gftea Thank you for your words! 
Great note! Will add it in the README 
But before the README, join the [talk](https://wearecommunity.io/events/kubernetes-in-rust) tomorrow, where @leon3s will answer this question in depth!

**Reply by gftea** [reply]
I think we need maximum 3 sentences to attract engineers to contribute

**Reply by mamaicode** [reply]
@gftea Updated 🦀

**Comment by 0xle0ne** [comment]
Hey, it's actually a good question, and to be honest you probably don't need Nanocl.
It's still in development and wont fit a **High availability production** as it lack of feature at this level.
The main reason why i started this project wasn't to fix Kubernetes or Nomad problem.
It's because i wanted to learn Rust and it's a fun subject that i wanted to explore.
Now the big difference with Kubernetes and other is the developers experiences i think.
I use Nanocl to start my micro services to avoid CORS and cookie problems,
it's allow me to create a DNS server for my development environment and just for that I'll love it.
After I'm done to pass in production i just tweak a little bit my development config, and we are good to go!

If you are interrested this is an example of my config:

```yaml
ApiVersion: v0.7
Kind: Deployment

Namespace: dev-nexthat

Resources:
  - Name: dns-dev-nexthat
    Kind: DnsRule
    Version: v0.1
    Config:
      Network: dev-nexthat.nsp
      Entries:
        - Name: store.dev.next-hat.wtf
          IpAddress: dev-nexthat.nsp
        - Name: api.dev.next-hat.wtf
          IpAddress: dev-nexthat.nsp
        - Name: auth.dev.next-hat.wtf
          IpAddress: dev-nexthat.nsp
        - Name: console.dev.next-hat.wtf
          IpAddress: dev-nexthat.nsp

  - Name: http-proxy-dev-nexthat
    Kind: ProxyRule
    Version: v0.4
    Config:
      Watch:
        - api.dev-nexthat
        - auth.dev-nexthat
        - console.dev-nexthat
      Rules:
        - Domain: api.dev.next-hat.wtf
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Target:
                CargoKey: api.dev-nexthat
                CargoPort: 8080

        - Domain: auth.dev.next-hat.wtf
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Version: 1.1
              Headers:
                - Upgrade $http_upgrade
                - Connection "Upgrade"
              Target:
                CargoKey: auth.dev-nexthat
                CargoPort: 3000

        - Domain: console.dev.next-hat.wtf
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Version: 1.1
              Headers:
                - Upgrade $http_upgrade
                - Connection "Upgrade"
              Target:
                CargoKey: console.dev-nexthat
                CargoPort: 3000

  - Name: stream-proxy-dev-nexthat
    Kind: ProxyRule
    Version: v0.4
    Config:
      Watch:
        - store.dev-nexthat
      Rules:
        - Network: dev-nexthat.nsp
          Protocol: Tcp
          Port: 26257
          Target:
            CargoKey: store.dev-nexthat
            CargoPort: 26257

Cargoes:
  - Name: store
    Container:
      Hostname: store.dev.next-hat.wtf
      Image: cockroachdb/cockroach:v22.2.7
      Tty: true
      HostConfig:
        Binds:
          - /opt/dev-store-nexthat:/cockroach/cockroach-data
      Env:
        - TZ=Europe/Paris
      Cmd:
        - start-single-node
        - --insecure
        - --listen-addr=:26257

  - Name: api
    Container:
      Image: ghcr.io/nxthat/nanocl-dev:dev
      Tty: true
      Env:
        - TZ=Europe/Paris
        - DATABASE_URL=postgres://root:root@store.dev.next-hat.wtf:26257/defaultdb?sslmode=disable
      HostConfig:
        Binds:
          - ./api:/project
          - /home/leone/.cargo/registry:/usr/local/cargo/registry
        Dns:
          - ${{ Namespaces.dev-nexthat.Gateway }}
      Cmd:
        - watch
        - -x
        - run

  - Name: auth
    Container:
      Image: node:18.16.0-slim
      Tty: true
      HostConfig:
        Binds:
          - ./auth:/project
        Dns:
          - ${{ Namespaces.dev-nexthat.Gateway }}
      Env:
        - TZ=Europe/Paris
        - DEFAULT_REDIRECT=https://next-hat.com
        - API_URL=http://api.dev.next-hat.wtf
      WorkingDir: /project
      Cmd:
        - sh
        - -c
        - |
          npm install
          npm run dev

  - Name: console
    Container:
      Image: node:18.16.0-slim
      Tty: true
      HostConfig:
        Binds:
          - ./console:/project
        Dns:
          - ${{ Namespaces.dev-nexthat.Gateway }}
      Env:
        - TZ=Europe/Paris
        - AUTH_URL=http://auth.dev.next-hat.wtf
        - API_URL=http://api.dev.next-hat.wtf
      WorkingDir: /project
      Cmd:
        - sh
        - -c
        - |
          npm install
          npm run dev
```
