### ISSUE TITLE
Feature: Enable HSTS configuration from the proxy rule

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#1247]
**Is your feature request related to a problem? Please describe.**
Currently, HSTS is automatically enabled when using Ssl. However, it also applies to subdomains by default, which isn't always desirable. Some setups require more control over how HSTS is applied — for example, disabling it for subdomains or fine-tuning preload behavior.

**Describe the solution you'd like**
Introduce a dedicated `Hsts` field in the proxy rule configuration to allow for better control.

Example of fine tuning:
```yaml
Data:
  Rules:
    - Domain: deploy-example.com
      Network: All
      Hsts:
        MaxAge: 31536000
        IncludeSubDomains: true
        Preload: false
        Always: true
      Locations:
        - Path: /
          Target:
            Key: deploy-example.global.c
            Port: 9000
```

Quickly enable recommended settings:
```
Data:
  Rules:
    - Domain: deploy-example.com
      Network: All
      Hsts: Recommended
      Locations:
        - Path: /
          Target:
            Key: deploy-example.global.c
            Port: 9000
```

Producing:
```
add_header Strict-Transport-Security "max-age=31536000" always;
```

Quickly produce strict settings:
```yaml
Data:
  Rules:
    - Domain: deploy-example.com
      Network: All
      Hsts: Strict
      Locations:
        - Path: /
          Target:
            Key: deploy-example.global.c
            Port: 9000
```

Producing:
```
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
```

**Additional context**
This proposal is part of the Nanocl proxy specification. The goal is to give users more control over security headers, while keeping simple use cases ergonomic.
