### ISSUE TITLE
RFC: ProxyRule

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#133]
Could be nice to brainstorm about how the resource ProxyRule should be defined.

We should be able to :

- enable a hostname to target a cargo at specific location using http and https
- redirect domain to another eg: www.domain.com -> domain.com
- enable tcp / udp to target a specific cargo at specific port
- pass extra http header ?

What else should we have ?

This is for now how look look like http and https to target a cargo at specific location:

-  Http
    ```yml
    Resources:
      - Name: resource-example
        Kind: ProxyRule
        Config:
          # List of cargo to watch updates
          Watch:
            - get-started@global
          Http:
            Domain: get-started.com
            Network: Public
            # Optional SSL config
            Ssl:
              Certificate: /path/to/cert
              CertificateKey: /path/to/cert
              DhParam: /path/to/dhparam
            # Http location
            Locations:
              - Path: /
                Target:
                  # The cargo to target for the location
                  Key: get-started@global
                  Port: 9000
    ```

- Stream
  ```yml
  Resources:
      - Name: resource-example
        Kind: ProxyRule
        Config:
          # List of cargo to watch updates
          Watch:
            - get-started@global
          Stream:
            Network: Public
            # The protocol to use Tcp | Udp
            Protocol: Tcp
            Port: 8888
            # Optional SSL config
            Ssl:
              Certificate: /path/to/cert
              CertificateKey: /path/to/cert
              DhParam: /path/to/dhparam
            # Http location
            Target:
              # The cargo to target for the location
              Key: get-started@global
              Port: 9000
  ```

**Comment by leon3s** [comment]
This is the first update that came in my mind

```yml
Resources:
  - Name: resource-example
    Kind: ProxyRule
    Config:
      Watch:
        - get-started@global
      Http:
        Domain: get-started.com
        Network: Public
        SslCertificate: /random/path/to/cert
        SslCertificateKey: /random/path/to/key
        SslDhParam: /random/path/to/param
        Locations:
          - Path: /
            Target:
              Key: get-started@global
              Port: 9000
```
