### ISSUE TITLE
Feature: Resource kind with url for hook

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#309]
**Is your feature request related to a problem? Please describe.**
We have to refactor the way `Custom Resource` can be created.

Currently we can create custom resource using this method:
```yaml
Type: Resource
ApiVersion: v0.6

Resources:
  - Name: VpnUser
    Kind: Custom
    Version: v0.1
    Config:
      title: VpnUser
      description: Create a new vpn user
      type: object
      required:
        - Username
      properties:
        Username:
          description: Cargo to watch for changes
          type: string
```

I want to refactor it so we can add an extra url along the custom schema.
Note: the schema use [json schema](https://json-schema.org) to be defined.

The refactor i want should access this configuration:
```yaml
Type: Resource
ApiVersion: v0.6

Resources:
  - Name: VpnUser
    Kind: Kind
    Version: v0.1
    Config:
      Url: my-custom-url.com
      Schema:
        title: VpnUser
        description: Create a new vpn user
        type: object
        required:
          - Username
        properties:
          Username:
            description: Cargo to watch for changes
            type: string
```

By changing this configuration, `ProxyRule` and `DnsRule` should now be defined as Resources and we should ensure they exist during boot time of the daemon. By default they just have and `Url` property pointing to the url already existing in the project starting with `unix://`

Note that both `Url` and `Schema` property can be optional but if both are unset on the creation of the new `Ressource Kind` we should return an error.

We should create a custom structure for example `ResourceKind`.
```rust
pub struct ResourceKind {
  pub  url: Option<String>,
  pub schema: Option<serde_json::Value>,
}
```
