### ISSUE TITLE
Feature: Save tcp and udp request inside database

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#332]
**Is your feature request related to a problem? Please describe.**
It's already done for http request, we should do it aswell for tcp and udp stream.

This is a daemon change you can see how i did it for inside `bin/nanocld/src/utils/proxy.rs`
You basically have to create a database model with [diesel](http://diesel.rs) then create the data when you receive it.
The receive process is already done. The `ncdproxy` should print a line starting with `#STREAM` when a tcp / udp request is fired.

**Comment by Narayanbhat166** [comment]
Hi @leon3s. I would like to work on this issue. I have experience working with diesel.

**Comment by 0xle0ne** [comment]
Hi @Narayanbhat166 sure go ahead! Let me know if you have problem or need additional information!

**Comment by Narayanbhat166** [comment]
Thankyou @leon3s. Yes, that would be helpful. 

I have looked at the file [proxy.rs](https://github.com/nxthat/nanocl/blob/4cbf3155434e81e0de3828f91ac63832da4610b9/bin/nanocld/src/utils/proxy.rs#L76) 
and found the part where TCP/UDP stream logs should be parsed and saved to the database. 
https://github.com/nxthat/nanocl/blob/4cbf3155434e81e0de3828f91ac63832da4610b9/bin/nanocld/src/utils/proxy.rs#L76

I have setup the docker locally and want to test out a tcp request so that I can know the structure of it. How can I achieve this? Is there any way I can get this structure without running the application and testing out a tcp request through the proxy?

**Comment by 0xle0ne** [comment]
Yeah you can see how it's structured there:

https://github.com/nxthat/nanocl/blob/4cbf3155434e81e0de3828f91ac63832da4610b9/bin/nproxy/nginx.conf#L132

and we have a commented structure that you could probably reuse there:

https://github.com/nxthat/nanocl/blob/4cbf3155434e81e0de3828f91ac63832da4610b9/bin/nanocld/src/models/http_metric.rs#L208


To know the structure without testing, but you will have to test at some point!
To trigger the log you can deploy this file:

```yml
Kind: Deployment
ApiVersion: v0.8

Namespace: global

# See all options:
# https://docs.next-hat.com/references/nanocl/resource
Resources:
  - Name: deploy-example.com
    Kind: ProxyRule
    Version: v0.5
    Config:
      Watch:
        - tcp-example.global.c
      Rules:
        - Network: Public
          Protocol: Tcp
          Port: 5555
          Target:
            Key: tcp-example.global.c
            Port: 9000


# See all options:
# https://docs.next-hat.com/references/nanocl/cargo
Cargoes:
  - Name: tcp-example
    Container:
      Image: nexthat/nanocl-get-started:latest
```

Then you can test by going on `http://localhost:5555`
