### ISSUE TITLE
Feature: Disable loggin for specific location

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#333]
**Is your feature request related to a problem? Please describe.**
The ncdproxy log everything, even if you send credentials for example a login form.
If you don't disable loggin for this specific path the credentials of the user aka login and password, will be in clear text inside the logs.
I want to have loggin enable by default as `zero trust policy`, but we should give the ability to disable it.

A configuration like this should be considered:

```yaml
Kind: Deployment
ApiVersion: v0.7

Namespace: global

Resources:
  - Name: deploy-example.com
    Kind: ProxyRule
    Version: v0.4
    Config:
      Watch:
        - deploy-example.global
        - deploy-example2.global
      Rules:
        - Domain: deploy-example.com
          Network: Public
          Locations:
            - Path: /
              Target:
                CargoKey: deploy-example.global
                CargoPort: 9000
            - Path: /users/login
              Target:
                CargoKey: deploy-example.global
                CargoPort: 9000
                Path: /users/login
                DisableLoggin: true

Cargoes:
  - Name: deploy-example
    Container:
      Image: nexthat/nanocl-get-started:latest
      Env:
        - APP=GET_STARTED1
```

Where `Path` and `DisableLoggin` are optinal values.
You have to take a look at [nginx](https://nginx.org).
