### ISSUE TITLE
Feature: Allow HTTP and STREAM Rules inside the same vector in ProxyRule

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#412]
**Is your feature request related to a problem? Please describe.**
Currently if we want to define tcp/udp raw proxy rule it have to be done in a separate ressource.
eg:

```yml
Resources:
  - Name: http-proxy-dev-nexthat
    Kind: ProxyRule
    Version: v0.5
    Config:
      Watch:
        - api.dev-nexthat.c
        - auth.dev-nexthat.c
        - console.dev-nexthat.c
      Rules:
        - Domain: auth.dev.next-hat.com
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Version: 1.1
              Headers:
                - Upgrade $http_upgrade
                - Connection "Upgrade"
              Target:
                Key: auth.dev-nexthat.c
                Port: 3000

        - Domain: console.dev.next-hat.com
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Version: 1.1
              Headers:
                - Upgrade $http_upgrade
                - Connection "Upgrade"
              Target:
                Key: console.dev-nexthat.c
                Port: 3000

  - Name: stream-proxy-dev-nexthat
    Kind: ProxyRule
    Version: v0.5
    Config:
      Watch:
        - store.dev-nexthat
      Rules:
        - Network: dev-nexthat.nsp
          Protocol: Tcp
          Port: 26258
          Target:
            Key: store.dev-nexthat
            Port: 26257
```

**Describe the solution you'd like**
i would like to be able to have tcp/udp stream inside the same array of rules
eg:

```yml
Resources:
  - Name: http-proxy-dev-nexthat
    Kind: ProxyRule
    Version: v0.5
    Config:
      Watch:
        - api.dev-nexthat.c
        - auth.dev-nexthat.c
        - console.dev-nexthat.c
      Rules:
        - Domain: auth.dev.next-hat.com
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Version: 1.1
              Headers:
                - Upgrade $http_upgrade
                - Connection "Upgrade"
              Target:
                Key: auth.dev-nexthat.c
                Port: 3000

        - Domain: console.dev.next-hat.com
          Network: dev-nexthat.nsp
          Locations:
            - Path: /
              Version: 1.1
              Headers:
                - Upgrade $http_upgrade
                - Connection "Upgrade"
              Target:
                Key: console.dev-nexthat.c
                Port: 3000

        - Network: dev-nexthat.nsp
          Protocol: Tcp
          Port: 26258
          Target:
            Key: store.dev-nexthat
            Port: 26257
```

**Additional context**
This is a `ncdproxy` change, we have to modify the structure and the enum located in `crates/nanocl_stubs/src/proxy.rs`
eg:
```rust
/// Proxy rules modes
#[derive(Debug, Clone)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(untagged, rename_all = "PascalCase"))]
pub enum ProxyRule {
  /// Redirect http trafic
  Http(ProxyRuleHttp),
  /// Redirect tcp and udp trafic
  Stream(ProxyRuleStream),
}
/// Define proxy rules to apply
#[derive(Debug, Clone)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "PascalCase"))]
pub struct ResourceProxyRule {
  /// Cargo to watch for changes
  pub watch: Vec<String>,
  /// The rule
  pub rules: Vec<ProxyRule>,
}

```

We will have to change how the files are generated aswell in `bin/ncdproxy/src/utils.rs` mainly.
