### ISSUE TITLE
Feature: Accept virtual machine in ProxyRule

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#413]
**Is your feature request related to a problem? Please describe.**
The virtual machine management feature start to be quite stable now.
It would be nice to be able to target virtual machine instance using `ProxyRule`

**Describe the solution you'd like**
This kind of config should be accepted and target the virtual machine
eg:

```yml
Resources:
  - Name: http-proxy-dev-nexthat
    Kind: ProxyRule
    Version: v0.5
    Config:
      Watch:
        - test-vm.global.v
      Rules:
        - Network: Public
          Protocol: Tcp
          Port: 2222
          Target:
            Key: test-vm.global.v
            Port: 22
```
