### ISSUE TITLE
Feature: Import virtual machine image from Statefile

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#414]
**Is your feature request related to a problem? Please describe.**
It will be a greater developers experience if we can import virtual machine images from the `Statefile`

**Describe the solution you'd like**
A configuration like this should be working
eg:

```yml
Kind: VirtualMachine
ApiVersion: v0.8

Namespace: global

VirtualMachineImages:
  - Name: ubuntu-22
    From: https://cloud-images.ubuntu.com/minimal/releases/jammy/release/ubuntu-22.04-minimal-cloudimg-amd64.img

VirtualMachines:
  - Name: vm-test
    Disk:
      Image: ubuntu-22
    HostConfig:
      Cpu: 2
      Memory: 2048
      Kvm: true
```

**Additional context**
I would like to avoid our daemon to download the file.
Instead we will download it on the local machine of the users where the command is run under `/tmp` and upload it on the daemon afterwards.
