### ISSUE TITLE
Feature: Enable boolean inside Statefile args

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#443]
**Is your feature request related to a problem? Please describe.**
Currently only one type is supported, the strings, it would be nice to have boolean aswell.

eg:

```yml
Kind: Deployment
ApiVersion: v0.8

Args:
  - Name: name
    Kind: String
  - Name: domain
    Kind: String
  - Name: image
    Kind: String
  - Name: port
    Kind: String
  - Name: enable-ssl
    Kind: boolean
```
