### ISSUE TITLE
Feature: nanocl state apply --remove-orphans

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#969]
**Is your feature request related to a problem? Please describe.**
Currently if a anything is delete from a statefile that we reapply nothing really append.

An option `--remove-orphans` like docker-compose provide should be considered.

To do so we will add on the cli side a metadata key : `nanocl.io/group` with value the path of the statefile.

Then we can query all related object from this statefile and see what doesn't exist anymore.

To make it more flexible, the group can be set by the user eg:

```yaml

ApiVersion: v0.14

Group: my-unique-group

# See all options:
# https://docs.next-hat.com/references/nanocl/objects/cargo
Cargoes:
- Name: cargo-example
  Metadata:
    Certbot: managed
  Container:
    Image: ghcr.io/next-hat/nanocl-get-started:latest
```

If the value of the group exist we use it as value from our `nanocl.io/group` metadata, if it doesn't we use the full path of the statefile.
